// Generated by CoffeeScript 1.10.0
(function() {
  jQuery(function($) {
    var $item, href, meta_key, name, orderby, results, url;
    results = [];
    for (name in art_PostTableColumns) {
      meta_key = art_PostTableColumns[name];
      $item = $("#" + name + " a");
      href = $item.attr("href");
      orderby = href.match(/orderby=(\w+)/)[1];
      href = href.replace(/orderby=(\w+)/, "orderby=meta_value");
      if (href.match(/meta_key=\w+/)) {
        href = href.replace(/meta_key=\w+/, "meta_key=" + meta_key);
      } else {
        href = href + ("&meta_key=" + meta_key);
      }
      $item.attr("href", href);
      url = location.href;
      if (url.match(/orderby=meta_value/) && url.match(new RegExp("meta_key=" + meta_key))) {
        $item.parent().addClass("sorted").removeClass("sortable");
        if (url.match(/order=asc/)) {
          $item.parent().addClass("asc").removeClass("desc");
        }
        if (url.match(/order=desc/)) {
          $item.parent().addClass("desc").removeClass("asc");
        }
        if (url.match(/order=asc/)) {
          $item.attr({
            "href": href.replace(/order=asc/, "order=desc")
          });
        }
        if (url.match(/order=desc/)) {
          $item.attr({
            "href": href.replace(/order=desc/, "order=asc")
          });
        }
        results.push($item.parent().siblings().each(function() {
          return $("a", this).attr("href", function(i, val) {
            return val.replace(/&meta_key=\w+/, "");
          });
        }));
      } else {
        results.push($item.parent().removeClass("sorted").addClass("sortable"));
      }
    }
    return results;
  });

}).call(this);
